config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts

  root 'static_pages#home'


  # get 'pages/index'

  get '/home', to: 'pages#home'
  get '/user/:id' => 'pages#profile'
  get '/explore', to: 'pages#explore'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts, dependent: :destroy
         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

         has_many :following, through: :active_relationships, source: followed

  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@uninove\.edu.br\z/, message: "Apenas e-mails @uninove.edu.br podem se registrar." }

  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user| user.permit(:name, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |user| user.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |user| user.permit(:name, :email, :current_password, :password_confirmation, :remember_me) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def home
    @posts = Post.all.where("user_id = ?", current_user.id)
    @newPost = Post.new
  end

  def profile
    if (User.find_by_username(params[:id]))
      @username = params[:id]
      @user = User.find_by_username(params[:id])
    else
      redirect_to root_path, :notice => "Usuário não encontrado!"
    end

    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new

    @fiveUsers = User.all.first(5)
  end

  def explore
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |f|
      if(@post.save)
        f.html { redirect_to home_path, notice: "Post criado com sucesso!"}
      else
        f.html {redirect_to home_path, notice: "Erro ao criar o post" }
      end
    end
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Uniblah! - A twitter Clone"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- <footer class="footer">
  <small>
    UniBlah! - 2017
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre",   about_path %></li>
      <li><%= link_to "Contato",   contact_path %></li>
    </ul>
  </nav>
</footer> -->

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/nav_user' %>
<% else %>
  <%= render 'layouts/nav_public' %>
<% end %>

app/views/layouts/_nav_public.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to('<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home'.html_safe, root_path) %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Explorar'.html_safe, explore_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navegação<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- <li role="separator" class="divider"></li> -->
            <li><%= link_to('Registrar', new_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Entrar', new_user_session_path) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<a name="top"></a>
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <img class="navbar-brand rounded-img" src="http://alexeitruhin.github.io/images/avatar-br.png">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to('<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home'.html_safe, root_path) %></li>
        <li><%= link_to '<span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Explorar'.html_safe, explore_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Buscar">
            </div>
          </form>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle dropdown-avatar" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-img" src="http://alexeitruhin.github.io/images/avatar-br.png" width="25px" height="25px"><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.username %>">Perfil</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Configurações', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li> 
          </ul>
        </li>
        <li type="button" class="btn btn-primary navbar-btn">Postar</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <% if params[:id] != nil %>
      <% @url = '/user/' + params[:id] %>
      <% if current_page?(@url) %>
        <img class="panel-image-preview profile-panel" src="/1500x500.jpg">
        <div class="row">
          <div class="col-sm-12" style="background-color: white;">
            <div class="container">
              <div class="col-md-3 col-sm-3 col-xs-12">
                esquerda
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12">
                centro
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="container">
      <span class="notice"><%= notice %></span>
      <span class="alert"><%= alert %></span>

      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/pages/explore.html.erb
<div class="row">

  <div class="col-xs-6 col-xs-offset-3">
    <% for @post in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body row">
          <div class="col-sm-2 col-xs-2">
            <img src="http://alexeitruhin.github.io/images/avatar-br.png" width="50px" height="50px">
          </div>
          <div class="col-sm-10 col-xs-10">
            <p class="post-title">
              <span class="post-owner">
                <%= @post.user.name %>
              </span>
              <span class="post-create-date" title="<%= l(@post.created_at, :format => "%d de %B de %Y as %H:%M") %>">
                @<%= @post.user.username %> - <%= time_ago_in_words(@post.created_at) %>
              </span>
            </p>
            <p class="post-content"><%= @post.content %></p>
          </div>
          <div class="col-sm-10 col-sm-offset-2">
            <p class="post-links">
              <span class="glyphicon glyphicon-comment glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-retweet glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-heart glyphi-links" aria-hidden="true"></span>
            </p>
          </div>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body" style="padding: 0px;">
        <div class="panel-image-hide-panel-body">
          <img class="panel-image-preview profile-panel-bg" src="/1500x500.jpg">
        </div>
        <div class="panel-footer text-center">
          <div class="row">
            <div class="col-sm-2">
              <img class="rounded-img avatar-size-medium" src="http://alexeitruhin.github.io/images/avatar-br.png">
            </div>
            <div class="col-sm-10 profile-info">
              <h4 class="text-left"><%= current_user.name %></h4>
              <h5 class="text-left">@<%= current_user.username %></h5>
            </div>
            <div class="col-sm-12">
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Posts<br>
                <h6><%= @posts.count %></h6>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Seguindo<br>
                <h6>10</h6>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Seguidores<br>
                <h6>10</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- <div class="panel panel-default">
      <div class="panel-body">
        trends
      </div>
    </div> -->
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= render '/components/post_form' %>
    <% for @post in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body row">
          <div class="col-sm-2 col-xs-2">
            <img class="rounded-img avatar-size-medium" src="http://alexeitruhin.github.io/images/avatar-br.png">
          </div>
          <div class="col-sm-10 col-xs-10">
            <p class="post-title">
              <span class="post-owner">
                <%= @post.user.name %>
              </span>
              <span class="post-create-date" title="<%= l(@post.created_at, :format => "%d de %B de %Y as %H:%M") %>">
                @<%= @post.user.username %> - <%= time_ago_in_words(@post.created_at) %>
              </span>
            </p>
            <p class="post-content"><%= @post.content %></p>
          </div>
          <div class="col-sm-10 col-sm-offset-2 col-xs-offset-2 col-xs-12">
            <p class="post-links">
              <span class="glyphicon glyphicon-comment glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-retweet glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-heart glyphi-links" aria-hidden="true"></span>
            </p>
          </div>
        </div>
      </div>
    <% end %>

    <div class="panel panel-default post-panel">
      <div class="panel-body row">
        <div class="col-sm-12">
        <center>
          <a href="#top">
            <p class="link-top">
              <img class="avatar-size-icon" src="http://alexeitruhin.github.io/images/avatar-br.png">
              Voltar para o topo <span class="glyphicon glyphicon-arrow-up glyphi-links" aria-hidden="true"></span>
            </p>
          </a>
        </center>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <p>follow</p>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <p style="opacity: 0.5; font-size: 90%;">2017 - UniBlah!</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/profile.html.erb
<div class="row">
  <div class="col-md-12">
    
  </div>
</div>
<div class="row">
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body" style="padding: 0px;">
        <div class="panel-image-hide-panel-body">
          <img class="panel-image-preview profile-panel-bg" src="/1500x500.jpg">
        </div>
        <div class="panel-footer text-center">
          <div class="row">
            <div class="col-sm-2">
              <img class="rounded-img avatar-size-medium" src="http://alexeitruhin.github.io/images/avatar-br.png">
            </div>
            <div class="col-sm-10 profile-info">
              <h4 class="text-left"><%= @user.name %></h4>
              <h5 class="text-left">@<%= @user.username %></h5>
            </div>
            <div class="col-sm-12">
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Posts<br>
                <h6><%= @posts.count %></h6>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Seguindo<br>
                <h6>10</h6>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-6 col-xs-4 text-left">
                Seguidores<br>
                <h6>10</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <% for @post in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body row">
          <div class="col-sm-2 col-xs-2">
            <img class="rounded-img avatar-size-medium" src="http://alexeitruhin.github.io/images/avatar-br.png">
          </div>
          <div class="col-sm-10 col-xs-10">
            <p class="post-title">
              <span class="post-owner">
                <%= @post.user.name %>
              </span>
              <span class="post-create-date" title="<%= l(@post.created_at, :format => "%d de %B de %Y as %H:%M") %>">
                @<%= @post.user.username %> - <%= time_ago_in_words(@post.created_at) %>
              </span>
            </p>
            <p class="post-content"><%= @post.content %></p>
          </div>
          <div class="col-sm-10 col-sm-offset-2 col-xs-offset-2 col-xs-12">
            <p class="post-links">
              <span class="glyphicon glyphicon-comment glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-retweet glyphi-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-heart glyphi-links" aria-hidden="true"></span>
            </p>
          </div>
        </div>
      </div>
    <% end %>

  </div>
  <div class="col-md-3 col-sm-3 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul>
          <% for @user in @fiveUsers do %>
            <li><a href="/user/<%= @user.username %>"><%= @user.username %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- <div class="panel panel-default">
      <div class="panel-body">
        <p>trends</p>
      </div>
    </div> -->
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "Sobre") %>
<h1>About</h1>
<p>
  static about page
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contato') %>
<h1>Página de Contato</h1>
<p>
  formulário aqui
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Ajuda") %>
<h1>Help</h1>
<p>
  static help page
</p>

app/views/static_pages/home.html.erb
<% if !user_signed_in? %>

<style type="text/css">
  body{
    background: 
      linear-gradient(
      rgba(0,0,0, 0.1),
      rgba(0,0,0, 0.1)),
      url('bg.jpg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
  }

  .container-index{
    margin-right: 15%;
    margin-left: 15%;
    font-weight: bold;
  }
  .text{
    color: white;
    font-weight: 300;
    font-size: 150%;
  }

</style>

<div class="container-index row home">
  <div class="col-md-12 titulo__home">
    <img src="logo.svg">
    <p class="text">
      Compartilhe suas ideias e pensamentos aqui
    </p>
  </div>
  <div class="col-md-12">
    <div class="sign-in col-md-6 col-sm-12"> 
      <%= link_to('Entrar', new_user_session_path, class: "btn btn-lg btn-uniblah") %> 
    </div>
    <div class="sign-up col-md-6 col-sm-12"> 
      <%= link_to('Registrar', new_user_registration_path, class: "btn btn-lg btn-uniblah") %>
    </div>
  </div>
</div>


<% else %>
  <script type="text/javascript">
    document.location = "/home";
  </script>
<% end %>

<!-- <div class="center jumbotron">
  <h1>Bem-vind@ ao UniBlah!</h1>

  <h2>
    Título impactante!!!
  </h2>

  
</div>
<%= link_to image_tag("logo.png", alt: "logo"),
            '#' %>
 -->

app/views/users/new.html.erb
<% provide(:title, 'Cadastre-se') %>
<h1>Cadastre-se</h1>
<p>página de cadastro de usuários</p>